### ISSUE TITLE
Use Formula.sha256 & SoftwareSpec#sha256

### ISSUE THREAD

**Issue by ajslater** [iveney/homebrew-mocha#2]
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/iveney/homebrew-mocha/realpath.rb:11:in `<class:Realpath>'
Please report this to the iveney/mocha tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/iveney/homebrew-mocha/realpath.rb:11:in `<class:Realpath>'
Please report this to the iveney/mocha tap!

**Comment by iveney** [comment]
Should be fixed in #3
